CKProje/Models/ErrorViewModel.cs
using System;

namespace CKProje.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CKProje/Controllers/HomeController.cs
using CKProje.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CKProje.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CKProje/Controllers/MusterilerController.cs
using CKDataAccess.Data;//ekledi
using CKModel.Models;//ekledik
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
namespace CKProje.Controllers
{
    public class MusterilerController : Controller
    {
        private readonly ApplicationDbContext _db;


        public MusterilerController(ApplicationDbContext db)
        {
            _db = db;
        }


        public IActionResult Index()
        {
            var objList = _db.Musteriler.ToList();
            return View(objList);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Musteriler obj)
        {
            if (ModelState.IsValid)
            {
                _db.Add(obj);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(obj);

        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");

            }

            var ob = await _db.Musteriler.FindAsync(id);
            return View(ob);
        }
        [HttpPost]

        public async Task<IActionResult> Edit(Musteriler ob)
        {
            if (ModelState.IsValid)
            {
                _db.Update(ob);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }


            return View(ob);
        }
        public async Task<IActionResult> Delete(int? id)
        {

            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var obj = await _db.Musteriler.FindAsync(id);
            return View(obj);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var obj = await _db.Musteriler.FindAsync(id);
            _db.Musteriler.Remove(obj);
            await _db.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

CKProje/Controllers/SiparislerController.cs
using CKDataAccess.Data;//ekledi
using CKModel.Models;//ekledik
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace CKProje.Controllers
{
    public class SiparislerController : Controller
    {
        private readonly ApplicationDbContext _db;


        public SiparislerController(ApplicationDbContext db)
        {
            _db = db;
        }


        public IActionResult Index()
        {
            var objList = _db.Siparisler.ToList();
            return View(objList);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Siparisler obj)
        {
            if (ModelState.IsValid)
            {
                _db.Add(obj);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(obj);

        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");

            }

            var ob = await _db.Siparisler.FindAsync(id);
            return View(ob);
        }
        [HttpPost]

        public async Task<IActionResult> Edit(Siparisler ob)
        {
            if (ModelState.IsValid)
            {
                _db.Update(ob);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }


            return View(ob);
        }
        public async Task<IActionResult> Delete(int? id)
        {

            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var obj = await _db.Siparisler.FindAsync(id);
            return View(obj);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var obj = await _db.Siparisler.FindAsync(id);
            _db.Siparisler.Remove(obj);
            await _db.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

CKProje/Controllers/UrunlerController.cs
using CKDataAccess.Data;//ekledi
using CKModel.Models;//ekledik
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace CKProje.Controllers
{
    public class UrunlerController : Controller
    {
        private readonly ApplicationDbContext _db;


        public UrunlerController(ApplicationDbContext db)
        {
            _db = db;
        }


        public IActionResult Index()
        {
            var objList = _db.Urunler.ToList();
            return View(objList);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Urunler obj)
        {
            if (ModelState.IsValid)
            {
                _db.Add(obj);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(obj);

        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");

            }

            var ob = await _db.Urunler.FindAsync(id);
            return View(ob);
        }
        [HttpPost]

        public async Task<IActionResult> Edit(Urunler ob)
        {
            if (ModelState.IsValid)
            {
                _db.Update(ob);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }


            return View(ob);
        }
        public async Task<IActionResult> Delete(int? id)
        {

            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var obj = await _db.Urunler.FindAsync(id);
            return View(obj);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var obj = await _db.Urunler.FindAsync(id);
            _db.Urunler.Remove(obj);
            await _db.SaveChangesAsync();

            return RedirectToAction("Index");
        }


    }
}

CKProje/Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>One Page Wonder - Start Bootstrap Template</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="css/styles.css" rel="stylesheet" />
    <link href="~/css/styles.css" rel="stylesheet" />

    <script src="~/js/scripts.js"></script>
</head>
<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
        <div class="container px-5">
            <a class="navbar-brand" href="#page-top">Ana Sayfa</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">

                    <li class="nav-item"><a class="nav-link text-break" asp-area="" asp-controller="Urunler" asp-action="Index">Urunler</a></li>
                    <li class="nav-item"><a class="nav-link text-break" asp-area="" asp-controller="Siparisler" asp-action="Index">Siparisler</a></li>
                    <li class="nav-item"> <a class="nav-link text-break" asp-area="" asp-controller="Musteriler" asp-action="Index">Musteriler</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Header-->
    <header class="masthead text-center text-black">
        <div class="masthead-content">
            <div class="container px-5">
                <h1 class="masthead-heading mb-0"style="color:beige">İnci Zarafeti </h1>
                <h2 class="masthead-subheading mb-0"style="color:beige"> Hep Sizinle</h2>
                <a class="btn btn-primary btn-xl rounded-pill mt-5 " href="#scroll">Daha Fazlası</a>
            </div>
        </div>
        <div class="bg-circle-1 bg-circle"></div>
        <div class="bg-circle-2 bg-circle"></div>
        <div class="bg-circle-3 bg-circle"></div>
        <div class="bg-circle-4 bg-circle"></div>
    </header>
    <!-- Content section 1-->
    <section id="scroll">
        <div class="container px-5">
            <div class="row gx-5 align-items-center">
                <div class="col-lg-6 order-lg-2">
                    <div class="p-5"><img class="img-fluid rounded-circle" src="assets/img/incitak.jpg" alt="..." /></div>
                </div>
                <div class="col-lg-6 order-lg-1">
                    <div class="p-5">
                        <h2 class="display-4">İnci diyarına hoşgeldiniz...</h2>
                        <p>Birbirinden güzel inciler ile yaşam sevincinizin artacağı mutlu günlerinizde size eşlik edecek olan inci koleksiyonlarımız</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Content section 2-->
    <section>
        <div class="container px-5">
            <div class="row gx-5 align-items-center">
                <div class="col-lg-6">
                    <div class="p-5"><img class="img-fluid rounded-circle" src="assets/img/incitaki2.jpg" alt="..." /></div>
                </div>
                <div class="col-lg-6">
                    <div class="p-5">
                        <h2 class="display-4">İnci diyarına hoşgeldiniz...</h2>
                        <p>Birbirinden güzel inciler ile yaşam sevincinizin artacağı mutlu günlerinizde size eşlik edecek olan inci koleksiyonlarımız</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Content section 3-->
    <section>
        <div class="container px-5">
            <div class="row gx-5 align-items-center">
                <div class="col-lg-6 order-lg-2">
                    <div class="p-5"><img class="img-fluid rounded-circle" src="assets/img/incitaki3.jpg"/></div>
                </div>
                <div class="col-lg-6 order-lg-1">
                    <div class="p-5">
                        <h2 class="display-4">İnci diyarına hoşgeldiniz...</h2>
                        <p>Birbirinden güzel inciler ile yaşam sevincinizin artacağı mutlu günlerinizde size eşlik edecek olan inci koleksiyonlarımız</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container-fluid"><p class="m-0 text-center text-white small">Copyright &copy; Your Website 2022</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
</body>
</html>

CKProje/Views/Musteriler/Create.cshtml
@model CKModel.Models.Musteriler

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <div class="align-content-md-end">


        <h1>Create</h1>

        <h4>Musteriler</h4>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="MusteriAdi" class="control-label"></label>
                        <input asp-for="MusteriAdi" class="form-control" />
                        <span asp-validation-for="MusteriAdi" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="UrunAdi" class="control-label"></label>
                        <input asp-for="UrunAdi" class="form-control" />
                        <span asp-validation-for="UrunAdi" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Index" class="btn btn-dark">Geri Dön</a>
        </div>

        @section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        }





    </div>
    </div>

CKProje/Views/Musteriler/Delete.cshtml
@model CKModel.Models.Musteriler

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div class="container">
    <div class="align-content-md-end">



        <h1>Müşteriler</h1>

        <h3>Silmek istediğinize emin misiniz ?</h3>
        <div>
            
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.MusteriAdi)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.MusteriAdi)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.UrunAdi)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.UrunAdi)
                </dd>
            </dl>

            <form asp-action="Delete">
                <input type="hidden" asp-for="MusteriID" />
                <input type="submit" value="Sil" class="btn btn-danger" /> |
                <a asp-action="Index" class="btn btn-dark">Geri Dön</a>
            </form>
        </div>







    </div>
    </div>

CKProje/Views/Musteriler/Edit.cshtml
@model CKModel.Models.Musteriler

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <div class="align-content-md-end">

        <h1>Müşteri Düzenle</h1>

        
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="MusteriID" />
                    <div class="form-group">
                        <label asp-for="MusteriAdi" class="control-label"></label>
                        <input asp-for="MusteriAdi" class="form-control" />
                        <span asp-validation-for="MusteriAdi" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="UrunAdi" class="control-label"></label>
                        <input asp-for="UrunAdi" class="form-control" />
                        <span asp-validation-for="UrunAdi" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Kaydet" class="btn btn-success" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Index" class="btn btn-dark">Geri Dön</a>
        </div>

        @section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        }




    </div>
    </div>

       

CKProje/Views/Musteriler/Index.cshtml
@model IEnumerable<CKModel.Models.Musteriler>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div class="container">
    <div class="align-content-md-end">
        <h1>Müşteriler Sayfası</h1>
        <br />
        <p>
            <a asp-action="Create" class="btn btn-success">Müşteri Ekle</a>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.MusteriAdi)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.UrunAdi)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.MusteriAdi)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UrunAdi)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.MusteriID" class="btn btn-primary">Düzenle </a>  |

                            <a asp-action="Delete" asp-route-id="@item.MusteriID" class="btn btn-danger">Sil</a>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
        <br />
        <div>
            <a class="btn btn-dark" asp-controller="Home" asp-action="Index">Anasayfaya Git</a>

        </div>

    </div>

</div>

CKProje/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CKProje</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-lg-2">
            <div class="container">
                @* <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CKProje</a>        *@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <!--<ul class="navbar-nav flex-grow-1">-->
                    @*<li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Urunler" asp-action="Index">Urunler</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Siparisler" asp-action="Index">Siparisler</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Musteriler" asp-action="Index">Musteriler</a>
            </li>*@
                    <!--</ul>-->
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid p-0 m-0">
        <main role="main" class="pb-3">
            <p><br />@RenderBody()</p>
        </main>
    </div> 

    <footer class="border-top footer text-muted"  >
        
        @*<div class="container">
            &copy; 2022 - CKProje - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>*@
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CKProje/Views/Siparisler/Create.cshtml
@model CKModel.Models.Siparisler

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}





<div class="container">
    <div class="align-content-md-end">




        <h1>Create</h1>

        <h4>Siparisler</h4>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="UrunAdi" class="control-label"></label>
                        <input asp-for="UrunAdi" class="form-control" />
                        <span asp-validation-for="UrunAdi" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SiparisTarihi" class="control-label"></label>
                        <input asp-for="SiparisTarihi" class="form-control" />
                        <span asp-validation-for="SiparisTarihi" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Maliyet" class="control-label"></label>
                        <input asp-for="Maliyet" class="form-control" />
                        <span asp-validation-for="Maliyet" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Index" class="btn btn-dark">Geri Dön</a>
        </div>

        @section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        }







    </div>
    </div>




     

CKProje/Views/Siparisler/Delete.cshtml
@model CKModel.Models.Siparisler

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}






<div class="container">
    <div class="align-content-md-end">

        <h1>Siparişler</h1>

        <h3>Silmek istediğinize emin misiniz ?</h3>
        <div>
         
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.UrunAdi)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.UrunAdi)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.SiparisTarihi)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.SiparisTarihi)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Maliyet)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Maliyet)
                </dd>
            </dl>

            <form asp-action="Delete">
                <input type="hidden" asp-for="SiparisID" />
                <input type="submit" value="Sil" class="btn btn-danger" /> |
                <a asp-action="Index" class="btn btn-dark">Geri Dön</a>
            </form>
        </div>


    </div>
    </div>





      

CKProje/Views/Siparisler/Edit.cshtml
@model CKModel.Models.Siparisler

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div class="container">
    <div class="align-content-md-end">

        <h1>Sipariş Düzenle</h1>

        
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="SiparisID" />
                    <div class="form-group">
                        <label asp-for="UrunAdi" class="control-label"></label>
                        <input asp-for="UrunAdi" class="form-control" />
                        <span asp-validation-for="UrunAdi" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SiparisTarihi" class="control-label"></label>
                        <input asp-for="SiparisTarihi" class="form-control" />
                        <span asp-validation-for="SiparisTarihi" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Maliyet" class="control-label"></label>
                        <input asp-for="Maliyet" class="form-control" />
                        <span asp-validation-for="Maliyet" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Kaydet" class="btn btn-success" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Index" class="btn btn-dark">Geri Dön</a>
        </div>

        @section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        }




    </div>
    </div>

CKProje/Views/Siparisler/Index.cshtml
@model IEnumerable<CKModel.Models.Siparisler>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div class="container">
    <div class="align-content-md-end">

        <h1>Sipariş Sayfası</h1>
        <br />
        <p>
            <a asp-action="Create" class="btn btn-success">Siparis Ekle</a>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.UrunAdi)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SiparisTarihi)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Maliyet)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.UrunAdi)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SiparisTarihi)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Maliyet)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.SiparisID" class="btn btn-primary">Düzenle </a>  |

                            <a asp-action="Delete" asp-route-id="@item.SiparisID" class="btn btn-danger">Sil</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <br />

        <a class="btn btn-dark" asp-controller="Home" asp-action="Index">Anasayfaya Git</a>


    </div>
    </div>



      

CKProje/Views/Urunler/Create.cshtml
@model CKModel.Models.Urunler

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="align-content-md-end">

        <h1>Create</h1>

        <h4>Urunler</h4>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="UrunAdi" class="control-label"></label>
                        <input asp-for="UrunAdi" class="form-control" />
                        <span asp-validation-for="UrunAdi" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Fiyat" class="control-label"></label>
                        <input asp-for="Fiyat" class="form-control" />
                        <span asp-validation-for="Fiyat" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Kaydet" class="btn btn-success" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Index" class="btn btn-dark">Geri Dön</a>
        </div>

        @section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        }



    </div>
    </div>


    

CKProje/Views/Urunler/Delete.cshtml
@model CKModel.Models.Urunler

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <div class="align-content-md-end">


        <h1>Ürünler</h1>

        <h3>Silmek istediğinize emin misiniz ?</h3>
        <div>
        
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.UrunAdi)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.UrunAdi)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Fiyat)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Fiyat)
                </dd>
            </dl>

            <form asp-action="Delete">
                <input type="hidden" asp-for="UrunID" />
                <input type="submit" value="Sil" class="btn btn-danger" /> |
                <a asp-action="Index" class="btn btn-dark">Geri Dön</a>
            </form>
        </div>


    </div>
    </div>